### ISSUE TITLE
Add Gulp Support

### ISSUE THREAD

**Issue by watsoncj** [ReadyTalk/gradle-readytalk-js#16]
I have a project that would really benefit from these conventions. However the project is using gulp (because gulp integrates well with ionic).

What would be the recommended approach for adding gulp support to `gradle-readytalk-js`?

**Comment by stormbeta** [comment]
This was added in 0.2.0 by automatically including the upstream gulp plugin (which is virtually identical to the existing grunt support, but for gulp).
